package cloud.xcan.angus.spec.commercial;

import cloud.xcan.angus.api.obf.Str0;

public class License {

  public static String SUBJECT = new Str0(
      new long[]{0x1E6B43C60AC22C6DL, 0x8423C94847116C1AL, 0xC4EE5C2A8A84EAB2L,
          0xD27DB35290719CD5L}).toString() /* => "XCan Product License" */;

  public static final String NAME = "XCBL";

  public static final String VERSION = "v1";

  public static final String CONTENT =
      "#------------------------------------------------------------------------------------#\n"
          + "#                         Copyright (c) 2021 XCan Company                            #\n"
          + "#                   XCan Business License Agreement 1.0 (XCBL-1.0)                   #\n"
          + "#                   http://www.xcan.cloud/licenses/XCBL-1.0.txt                    #\n"
          + "#------------------------------------------------------------------------------------#\n"
          + "\n"
          + "This Software License Agreement (the \"Agreement\") is made by and between\n"
          + "XiaoCan Technology (Beijing) Co., Ltd. (\"Licensor\") and [Licensee] (\"Licensee\").\n"
          + "\n"
          + "## 1. License Grant\n"
          + "\n"
          + "1.1. Licensor hereby grants to Licensee a license to install and use the software product (the \"Software\").\n"
          + "1.2. After the recipient of \"Licensor\" (including R&D and testing personnel, etc.) is authorized to\n"
          + "  view and modify the source code, but are prohibited from modifying, copying, distributing or using\n"
          + "  it for non-licensor commercial purposes.\n"
          + "\n"
          + "## 2. Restrictions\n"
          + "\n"
          + "2.1. Licensee may not sell, rent, lease, distribute, or otherwise provide any copies of the Software\n"
          + "  or related licenses to any third party without the prior written consent of Licensor.\n"
          + "2.2. Licensee may not modify, translate, reverse engineer, or decompile the Software, or create any\n"
          + "  derivative works based on the Software.\n"
          + "2.3. Licensee may not use any part or all of the Software for any commercial purposes without the\n"
          + "  prior written consent of Licensor.\n"
          + "2.4. Licensor may revoke this license at any time if Licensee violates any provision of this Agreement,\n"
          + "  and Licensee must immediately cease using the Software and delete all files related to the Software.\n"
          + "\n"
          + "## 3. Warranty\n"
          + "\n"
          + "3.1. Licensor warrants that it has full, transferrable, exclusive, and irrevocable ownership and\n"
          + "  control of the Software.\n"
          + "3.2. Licensor warrants that the Software is free from viruses, trojan horses, malware, adware, spyware,\n"
          + "  or any other harmful programs, at the time of delivery.\n"
          + "\n"
          + "## 4. Disclaimer\n"
          + "\n"
          + "4.1. The Software is provided \"as is\" and Licensor makes no representation or warranties of any kind,\n"
          + "  express or implied, with respect to the Software's fitness for a particular purpose, accuracy, or reliability.\n"
          + "4.2. Licensor shall not be liable for any direct or indirect damages or losses resulting from Licensee's\n"
          + "  use or inability to use the Software.\n"
          + "\n"
          + "## 5. Applicable Law\n"
          + "\n"
          + "This Agreement shall be governed by and construed in accordance with the laws of the jurisdiction in\n"
          + "which the Software is used. Any dispute arising out of or in connection with this Agreement shall be\n"
          + "submitted to the jurisdiction of the courts of the jurisdiction in which the Software is used.\n"
          + "\n"
          + "## 6.Entire Agreement\n"
          + "\n"
          + "This Agreement constitutes the entire agreement between Licensor and Licensee and supersedes all prior\n"
          + "oral or written communications or agreements relating to the Software.\n"
          + "\n"
          + "## 7. Recipient Infringement\n"
          + "\n"
          + "7.1. The licensor has the right to require the recipient to immediately stop infringing the software copyright.\n"
          + "7.2. The recipient shall compensate the software copyright owner for direct economic losses suffered as\n"
          + "  a result of any infringement, including reduced software sales of the infringed party, legal fees, and\n"
          + "  other losses resulting from the infringement.\n"
          + "7.3. The recipient shall compensate the software copyright owner for other indirect economic losses suffered\n"
          + "   as a result of any infringement, such as damage to reputation or image.\n"
          + "7.4. If the recipient intentionally infringes the software copyright or maliciously cracks the software,\n"
          + "   the recipient shall be deemed to accept the licensor's demand for double compensation.\n"
          + "\n"
          + "## 8. Acceptance of License\n"
          + "\n"
          + "Licensee's use of the Software indicates acceptance of all the terms and conditions of this Agreement.\n"
          + "If Licensee does not agree to any provision of this Agreement, Licensee may not use the Software.\n"
          + "\n"
          + "Licensor: XiaoCan Technology (Beijing) Co., Ltd.\n"
          + "Date: [Date]\n"
          + "Licensee Signature: [Signature]\n"
          + "\n"
          + "\n"
          + "特此许可证，本商业软件许可证（以下简称“许可证”）是由晓蚕科技（北京）有限公司（以下简称“许可方”）授权（以下简称“收件人”）\n"
          + "使用许可方的软件产品（以下简称“软件”）。\n"
          + "\n"
          + "## 1. 许可范围\n"
          + "\n"
          + "1.1. 收件人被授权安装和使用本软件。\n"
          + "1.2. “许可方”收件人（包括研发、测试人员等）被授权查看和修改源代码后，不得对其进行修改、复制、分发等用于非“许可方”商业目的用途。\n"
          + "\n"
          + "## 2. 限制\n"
          + "\n"
          + "2.1. 收件人不得转让、出售、租赁、分发或以其他方式提供该软件的任何副本或相关许可证，除非已经获得许可方书面授权。\n"
          + "2.2. 收件人不得修改、翻译、反编译或反汇编该软件或创建该软件的派生作品。\n"
          + "2.3. 未经许可方书面授权，收件人不得使用该软件的任何部分或全部进行商业用途。\n"
          + "2.4. 许可方有权随时撤销本许可证，如果收件人违反了本许可证的任何规定，则收件人必须立即停止使用该软件并删除所有与该软件相关的文件。\n"
          + "\n"
          + "## 3. 保证\n"
          + "\n"
          + "3.1. 许可方保证其对该软件拥有完全的、可转让的、排他的和不可撤销的所有权及控制权。\n"
          + "3.2. 许可方保证该软件在交付时是没有病毒、木马、恶意软件、广告软件、间谍软件或其他有害程序的。\n"
          + "\n"
          + "## 4. 免责声明\n"
          + "\n"
          + "4.1. 该软件是按“原样”提供的，许可方不对该软件的适用性、准确性和可靠性作出任何保证或陈述。\n"
          + "4.2. 许可方不对收件人因使用或无法使用该软件而导致的任何直接或间接损失或损害承担任何责任。\n"
          + "\n"
          + "## 5. 适用法律\n"
          + "\n"
          + "本许可证受适用法律管辖，除非有其他书面约定，否则任何争议都应提交给该法律管辖区的有管辖权的法院解决。\n"
          + "\n"
          + "## 6. 完整协议\n"
          + "\n"
          + "本许可证构成许可方和收件人之间的完整协议，取代了所有口头或书面的通信、协议或其他安排。\n"
          + "\n"
          + "## 7. 收件人侵权\n"
          + "\n"
          + "7.1. 许可方有权要求收件人立即停止侵犯软件版权的行为。\n"
          + "7.2. 收件人需赔偿软件版权所有者因侵权行为所遭受的直接经济损失，包括被侵权方的软件销售额减少、维权费用和其他因侵权行为造成的损失等。\n"
          + "7.3. 收件人需赔偿软件版权所有者因侵权行为所遭受的其他间接经济损失，如名誉损失、形象损失等。\n"
          + "7.4. 如果收件人故意侵犯软件版权或者具有恶意破解，收件人被视为接受许可方加倍赔偿要求。\n"
          + "\n"
          + "## 8. 接受许可\n"
          + "\n"
          + "收件人使用该软件表示接受本许可证的所有条款和条件。如果收件人不同意本许可证的任何条款和条件，则不得使用该软件。\n"
          + "\n"
          + "许可方：晓蚕科技（北京）有限公司\n"
          + "日期：[Date]\n"
          + "收件人签名：[Signature]";
}
