server:
  port: 9021

eureka:
  client:
    healthcheck:
      enabled: true
    eureka-connection-idle-timeout-seconds: 10
    initial-instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
    serviceUrl:
      defaultZone: http://${DISCOVERY_SECURITY_USER_NAME:discovery}:${DISCOVERY_SECURITY_USER_PASSD:discovery}@${DISCOVERY_HOST:localhost}:${DISCOVERY_PORT:1801}/eureka/
  instance:
    appname: '@artifactId@'
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/swagger-ui/
    health-check-url-path: /actuator/health

xcan:
  core:
    enabled: true
  global:
    cors:
      startWithPaths: [ '/' ]
      credentials: true
      origin: '*'
      headers: '*'
      methods: 'POST, GET, PUT, DELETE, PATCH, HEAD'
  idgen:
    enabled: false
  datasource:
    enabled: true
    commonlink:
      enabled: false
    extra:
      entityPackages:
        - cloud.xcan.angus.domain
  redis:
    enabled: false
  l2cache:
    enabled: false
  jackson:
    defaultPropertyInclusion: always
    dateFormat: yyyy-MM-dd HH:mm:ss
    timeZone: ${info.app.timezone}
    generator:
      write_numbers_as_strings: true
  validator:
    enabled: true
    extraMessages:
      - classpath:/i18n/messages-restapi-sample

info:
  app:
    name: '@project.name@'
    editionType: '@editionType@'
    version: '@project.version@'
    artifactId: '@artifactId@'
    instanceId: ${spring.cloud.client.ip-address}:${server.port}
    description: '@project.description@'
    timezone: ${TIMEZONE:Asia/Shanghai}
    profile: '@profile.active@'
    runtime: ${RUNTIME:HOST}
    license: XCan Business License, Version 1.0
    licenseUrl: http://www.xcan.cloud/licenses/XCBL-1.0
    organization: '@organization.name@'
    organizationUrl: '@organization.url@'

spring:
  application:
    name: '@artifactId@'
  profiles:
    active: '@profile.active@'
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /pubapi/h2-console # http://localhost:9090/pubapi/h2-console
      settings:
        trace: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  security:
    oauth2:
      resource-server:
        opaque-token:
          client-id: client-credentials-introspect-client
          client-secret: secret
          introspection-uri: http://localhost:9090/oauth2/introspect
  # JPA Configuration Parameters
  jpa:
    hibernate:
      ddl-auto: validate
    #show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 5
          time_zone: ${info.app.timezone}
        order_inserts: true
        order_updates: true
        enable_lazy_load_no_trans: true
        session_factory:
    open-in-view: false

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  open-api:
    info:
      title: RESTFul api sample
      description: RESTFul api docs test

logging:
  config: classpath:spring-logback.xml
  level:
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.springframework.cloud: WARN
  file:
    path: ${log.dir:logs}

management:
  endpoints:
    web:
      exposure:
        include:
          - enums
          - systemlog
          - appworkspace
          - health
          - info
          - metrics
          - serviceregistry
  endpoint:
    enums:
      enabled: true
    health:
      show-details: always

