package cloud.xcan.angus.core.spring.env;

public interface EnvKeys {

  /* SpringBoot */
  String APP_NAME = "info.app.name";
  String APP_VERSION = "info.app.version";
  String APP_EDITION = "info.app.editionType";

  /* Installation */
  String INSTALL_APPS = "INSTALL_APPS";
  String INSTALL_TYPE = "INSTALL_TYPE";
  String DATABASE_TYPE = "DATABASE_TYPE";
  String RUNTIME = "RUNTIME";

  String TENANT_ID = "TENANT_ID";
  String TENANT_NAME = "TENANT_NAME";

  /* AngusGM */
  String GM_HOST = "GM_HOST";
  String GM_PORT = "GM_PORT";
  String GM_WEBSITE = "GM_WEBSITE";
  String GM_PLUGIN_LOADED = "GM_PLUGIN_LOADED";
  String GM_PLUGIN_IGNORED = "GM_PLUGIN_IGNORED";
  String GM_CLOUD_APIS_URL_PREFIX = "GM_CLOUD_APIS_URL_PREFIX";
  String GM_APIS_URL_PREFIX = "GM_APIS_URL_PREFIX";

  String GM_APP_OPEN_DATE = "GM_APP_OPEN_DATE";
  String GM_APP_EXPIRATION_DATE = "GM_APP_EXPIRATION_DATE";

  String STORAGE_FILES_PROXY_ADDRESS = "STORAGE_FILES_PROXY_ADDRESS";

  /* AngusGM - Administrator */
  String GM_ADMIN_USER_ID = "GM_ADMIN_USER_ID";
  String GM_ADMIN_FULL_NAME = "GM_ADMIN_FULL_NAME";
  String GM_ADMIN_EMAIL = "GM_ADMIN_EMAIL";
  String GM_ADMIN_USERNAME = "GM_ADMIN_USERNAME";
  String GM_ADMIN_PASSWORD = "GM_ADMIN_PASSWORD";
  String GM_ADMIN_ENCRYPTED_PASSWORD = "GM_ADMIN_ENCRYPTED_PASSWORD";

  /* AngusGM - Database */
  String GM_DB_HOST = "GM_DB_HOST";
  String GM_DB_PORT = "GM_DB_PORT";
  String GM_DB_NAME = "GM_DB_NAME";
  String GM_DB_USER = "GM_DB_USER";
  String GM_DB_PASSWORD = "GM_DB_PASSWORD";

  /* AngusTester */
  String TESTER_HOST = "TESTER_HOST";
  String TESTER_PORT = "TESTER_PORT";
  String TESTER_WEBSITE = "TESTER_WEBSITE";
  String TESTER_PLUGIN_LOADED = "TESTER_PLUGIN_LOADED";
  String TESTER_PLUGIN_IGNORED = "TESTER_PLUGIN_IGNORED";
  String TESTER_APIS_SERVER_URL = "TESTER_APIS_SERVER_URL";

  String PROXY_STARTUP_IN_TESTER = "PROXY_STARTUP_IN_TESTER";

  /* AngusTester - Database */
  String TESTER_DB_HOST = "TESTER_DB_HOST";
  String TESTER_DB_PORT = "TESTER_DB_PORT";
  String TESTER_DB_NAME = "TESTER_DB_NAME";
  String TESTER_DB_USER = "TESTER_DB_USER";
  String TESTER_DB_PASSWORD = "TESTER_DB_PASSWORD";

  /* Redis */
  String REDIS_DEPLOYMENT = "REDIS_DEPLOYMENT";
  String REDIS_HOST = "REDIS_HOST";
  String REDIS_PORT = "REDIS_PORT";
  String REDIS_PASSWORD = "REDIS_PASSWORD";
  String REDIS_SENTINEL_MASTER = "REDIS_SENTINEL_MASTER";
  String REDIS_NODES = "REDIS_NODES";

  /* Statics */
  String VITE_GM_URL_PREFIX = "VITE_GM_URL_PREFIX";
  String VITE_TESTER_URL_PREFIX = "VITE_TESTER_URL_PREFIX";

}
