package cloud.xcan.angus.security.model;

public interface SecurityConstant {

  String INTROSPECTION_CLAIM_NAMES_PRINCIPAL = "principal";
  String INTROSPECTION_CLAIM_NAMES_PERMISSION = "permissions";
  String INTROSPECTION_CLAIM_NAMES_GRANT_TYPE = "grant_type";

  String INTROSPECTION_CLAIM_NAMES_USERNAME = "username";
  String INTROSPECTION_CLAIM_NAMES_ENABLED = "enabled";
  String INTROSPECTION_CLAIM_NAMES_ACCOUNT_NON_EXPIRED = "accountNonExpired";
  String INTROSPECTION_CLAIM_NAMES_ACCOUNT_NON_LOCKED = "accountNonLocked";
  String INTROSPECTION_CLAIM_NAMES_CREDENTIALS_NON_EXPIRED = "credentialsNonExpired";
  String INTROSPECTION_CLAIM_NAMES_ID = "id";
  String INTROSPECTION_CLAIM_NAMES_FIRST_NAME = "firstName";
  String INTROSPECTION_CLAIM_NAMES_LAST_NAME = "lastName";
  String INTROSPECTION_CLAIM_NAMES_FULL_NAME = "fullName";
  //String INTROSPECTION_CLAIM_NAMES_PASSWORD_STRENGTH = "passwordStrength";
  String INTROSPECTION_CLAIM_NAMES_SYS_ADMIN = "sysAdmin";
  String INTROSPECTION_CLAIM_NAMES_TO_USER = "toUser";
  String INTROSPECTION_CLAIM_NAMES_MOBILE = "mobile";
  String INTROSPECTION_CLAIM_NAMES_EMAIL = "email";
  String INTROSPECTION_CLAIM_NAMES_MAIN_DEPT_ID = "mainDeptId";
  String INTROSPECTION_CLAIM_NAMES_PASSWORD_EXPIRED_DATE = "passwordExpiredDate";
  String INTROSPECTION_CLAIM_NAMES_LAST_MODIFIED_PASSWORD_DATE = "lastModifiedPasswordDate";
  String INTROSPECTION_CLAIM_NAMES_EXPIRED_DATE = "expiredDate";
  String INTROSPECTION_CLAIM_NAMES_TENANT_ID = "tenantId";
  String INTROSPECTION_CLAIM_NAMES_TENANT_NAME = "tenantName";
  String INTROSPECTION_CLAIM_NAMES_TENANT_REAL_NAME_STATUS = "tenantRealNameStatus";
  String INTROSPECTION_CLAIM_NAMES_COUNTRY = "country";
  String INTROSPECTION_CLAIM_NAMES_CLIENT_SOURCE = "clientSource";
  String INTROSPECTION_CLAIM_NAMES_DEVICE_ID = "deviceId";
  String INTROSPECTION_CLAIM_NAMES_DIRECTORY_ID = "directoryId";
  String INTROSPECTION_CLAIM_NAMES_DEFAULT_LANGUAGE = "defaultLanguage";
  String INTROSPECTION_CLAIM_NAMES_DEFAULT_TIMEZONE = "defaultTimeZone";

  String INTROSPECTION_CLAIM_NAMES_CLIENT_ID_ISSUED_AT = "clientIdIssuedAt";
  String INTROSPECTION_CLAIM_NAMES_CLIENT_SECRET_EXPIRES_AT = "clientSecretExpiresAt";
  String INTROSPECTION_CLAIM_NAMES_CLIENT_ID = "clientId";
  String INTROSPECTION_CLAIM_NAMES_CLIENT_NAME = "clientName";
  String INTROSPECTION_CLAIM_NAMES_SCOPES = "scopes";
  String INTROSPECTION_CLAIM_NAMES_DESCRIPTION = "description";
  // String INTROSPECTION_CLAIM_NAMES_ENABLED = "enabled";
  String INTROSPECTION_CLAIM_NAMES_PLATFORM = "platform";
  //String INTROSPECTION_CLAIM_NAMES_CLIENT_SOURCE = "source";
  String INTROSPECTION_CLAIM_NAMES_BIZ_TAG = "bizTag";
  // String INTROSPECTION_CLAIM_NAMES_TENANT_ID = "tenantId";
  // String INTROSPECTION_CLAIM_NAMES_TENANT_NAME = "tenantName";

}
